safe: true
markdown: kramdown
exclude: [ assets ]
permalink: /:title.html

default_theme: yandex
default_width: 792
default_lang: ru
default_body_class: list

kramdown:
  enable_coderay: false

presentation:
    title: Следующий шаг в эволюции BE*
    service: Расписания

author:
    name: Арсений Форштретер
    position: Старший разработчик интерфейсов

progress: true
